<?php
// Define BASEPATH to allow direct script access (simulating CI environment if needed, 
// but easier to just use standard CI bootstrapping if possible, or raw PHP for DB test)

// Since bootstrapping CI from outside index.php can be tricky without right paths,
// we will try to mimic a controller or use a dedicated test file that includes index.php logic
// OR simpler: we create a controller 'Test.php' if we can access the URL.
// But user cannot access new URLs easily? 
// Let's make a file in the root that loads CI.

define('ENVIRONMENT', 'development');
$system_path = 'system';
$application_folder = 'application';

if (realpath($system_path) !== FALSE) {
	$system_path = realpath($system_path).'/';
}
$system_path = rtrim($system_path, '/').'/';
define('BASEPATH', str_replace("\\", "/", $system_path));
define('FCPATH', dirname(__FILE__).'/');
define('APPPATH', $application_folder.'/');
define('VIEWPATH', $application_folder.'/views/');

require_once(BASEPATH.'core/Common.php');
require_once(BASEPATH.'core/Controller.php');
require_once(BASEPATH.'core/Config.php');
require_once(BASEPATH.'core/URI.php');
require_once(BASEPATH.'core/Router.php');
require_once(BASEPATH.'core/Input.php');
require_once(BASEPATH.'core/Output.php');
require_once(BASEPATH.'core/Security.php');
require_once(BASEPATH.'core/Lang.php');
require_once(BASEPATH.'core/Loader.php');
require_once(BASEPATH.'core/Model.php');
require_once(BASEPATH.'database/DB.php');

// Custom Test Logic
echo "Starting Test...\n";

try {
    $db =& DB();
    echo "Database Connected.\n";
    
    // 1. Check if 'happy_story' table exists
    if (!$db->table_exists('happy_story')) {
        die("ERROR: Table 'happy_story' does not exist.\n");
    }
    echo "Table 'happy_story' exists.\n";

    // 2. Attempt to Insert a Dummy Story
    $data = array(
        'title' => 'Test Story ' . date('H:i:s'),
        'description' => 'This is a test story generated by the debug script.',
        'date' => date('Y-m-d'),
        'program_date' => date('Y-m-d'),
        'legion_id' => 0, // Simulating Super Admin/No Legion
        'partner_name' => 'Test Partner',
        'program_area' => 'Test Area',
        'legion_name' => 'Test Legion',
        'area_name' => 'Test Location',
        'approval_status' => 1,
        'image' => '',
        'posted_by' => 1 // Assuming 1 is a valid admin ID
    );

    echo "Attempting insert with data: " . json_encode($data) . "\n";
    
    if ($db->insert('happy_story', $data)) {
        echo "SUCCESS: Insert Query Executed.\n";
        $insert_id = $db->insert_id();
        echo "Inserted ID: " . $insert_id . "\n";
        
        // 3. Verify Retrieval
        $query = $db->get_where('happy_story', array('happy_story_id' => $insert_id));
        if ($query->num_rows() > 0) {
            echo "VERIFIED: Record found in database.\n";
            print_r($query->row_array());
        } else {
            echo "ERROR: Insert reported success but record not found.\n";
        }
    } else {
        echo "ERROR: Insert Failed.\n";
        print_r($db->error());
    }

} catch (Exception $e) {
    echo "EXCEPTION: " . $e->getMessage() . "\n";
}
?>
